box/urls.py
from django.urls import path
from box.views import BaseViewBox

urlpatterns = [
    path('', BaseViewBox.as_view()),
]

mail/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('box.urls')),
    path('admin/', admin.site.urls),
]

box/models.py
from django.db import models

# Create your models here.

class Email(models.Model):
    adress = models.EmailField(max_length=70)
    subject = models.CharField(max_length=100)
    text = models.TextField()

box/views.py
from django.shortcuts import render
from django.views.generic import View, ListView
from box.models import Email

class BaseViewBox(ListView):

    model = Email
    template_name = 'box/base.html'

templates/box/base.html
 <!DOCTYPE html>
<!-- Template by html.am -->
{% load static %}

 <html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>2 Column Layout &mdash; Left Menu with Header &amp; Footer</title>

        <link rel="stylesheet" href="{% static 'css/style.css' %}">
{# TODO migrate this stylesheet to file#}
        <style type="text/css">
            body {
                margin:0;
                padding:0;
                font-family: Sans-Serif;
                line-height: 1.5em;
            }

            #header {
                background: #ccc;
                height: 100px;
            }

            #header h1 {
                margin: 0;
                padding-top: 15px;
            }

            main {
                padding-bottom: 10010px;
                margin-bottom: -10000px;
                float: left;
                width: 100%;
            }

            #nav {
                padding-bottom: 10010px;
                margin-bottom: -10000px;
                float: left;
                width: 230px;
                margin-left: -100%;
                background: #eee;
            }

            #footer {
                clear: left;
                width: 100%;
                background: #ccc;
                text-align: center;
                padding: 4px 0;
            }

            #wrapper {
                overflow: hidden;
            }

            #content {
                margin-left: 230px; /* Same as 'nav' width */
            }

            .innertube {
                margin: 15px; /* Padding for content */
                margin-top: 0;
            }

            p {
                color: #555;
            }

            nav ul {
                list-style-type: none;
                margin: 0;
                padding: 0;
            }

            nav ul a {
                color: darkgreen;
                text-decoration: none;
            }
        </style>

	</head>

	<body>

		<header id="header">
			<div class="innertube">
				<h1>Simple gmail</h1>
			</div>
		</header>

		<div id="wrapper">

			<main>
				<div id="content">
					<div class="innertube">
						<h1>Subject</h1>
                        {% include "box/subject_list.html" %}
					</div>
				</div>
			</main>

			<nav id="nav">
				<div class="innertube">
					<h3>Author</h3>
                    {% include "box/email_list.html" %}
				</div>
			</nav>

		</div>

		<footer id="footer">
			<div class="innertube">
				<p>Footer...</p>
			</div>
		</footer>

	</body>
</html>

templates/box/email_list.html
<ul>
    {% for email in object_list %}
        <li>{{ email.adress }}</li>
    {% endfor %}
</ul>

templates/box/subject_list.html
<ul>
    {% for email in object_list %}
        <li>{{ email.subject }}</li>
    {% endfor %}
</ul>